ARG JENKINS_AGENT_IMAGE_TYPE
ARG JENKINS_AGENT_IMAGE_TAG
ARG JENKINS_AGENT_SSH_PUBKEY
FROM jenkins/${JENKINS_AGENT_IMAGE_TYPE}:${JENKINS_AGENT_IMAGE_TAG} as ssh-agent
USER root
COPY --chown=jenkins "${JENKINS_AGENT_SSH_PUBKEY}" "${JENKINS_AGENT_HOME}"/.ssh/mykey