ARG JENKINS_AGENT_IMAGE_TYPE
ARG JENKINS_AGENT_IMAGE_TAG
ARG JENKINS_AGENT_SSH_PUBKEY
ARG JENKINS_BASE_REPO
FROM jenkins/${JENKINS_AGENT_IMAGE_TYPE}:${JENKINS_AGENT_IMAGE_TAG} as ssh-agent
USER root
COPY --chown=jenkins "${JENKINS_AGENT_SSH_PUBKEY}" "${JENKINS_BASE_REPO}"/.ssh/jenkins_agent.pub