services:
  jenkins-server:
    container_name: jenkins-main
    networks:
      jenkins-network:
        aliases:
          - jenkins-main.service
    user: root
    privileged: true
    image: bernardbdas/jenkins-server
    build:
      context: Dockerfiles
      dockerfile: server.Dockerfile
      args:
        # CONTAINER_NAME: ${JENKINS_SERVER_CONTAINER_NAME}
        IMAGE_TYPE: ${JENKINS_SERVER_IMAGE_TYPE}
        IMAGE_TAG: ${JENKINS_SERVER_IMAGE_TAG}
        WORKDIR: ${JENKINS_SERVER_WORKDIR}
        HOSTDIR: ${JENKINS_SERVER_HOSTDIR}
        # JAVA_OPTS: ${JAVA_OPTS}
    env_file:
      - path: .env
        required: true
    volumes:
      - ${JENKINS_SERVER_HOSTDIR}:${JENKINS_SERVER_WORKDIR}
    ports:
      - 8080:8080
      - 50000:50000
    # environment:
    #   CONTAINER_NAME: jenkins-main
    #   HOSTDIR: jenkins-main.container

  jenkins-agent-0:
    container_name: jenkins-agent-0
    networks:
      jenkins-network:
        aliases:
          - jenkins-agent-0.service
    user: root
    privileged: true
    image: bernardbdas/jenkins-ssh-agent
    build:
      context: Dockerfiles
      dockerfile: agent.Dockerfile
      args:
        # CONTAINER_NAME: ${JENKINS_AGENT_CONTAINER_NAME}
        IMAGE_TYPE: ${JENKINS_SERVER_IMAGE_TYPE}
        IMAGE_TAG: ${JENKINS_SERVER_IMAGE_TAG}
        WORKDIR: ${JENKINS_SERVER_WORKDIR}
        HOSTDIR: /0-${JENKINS_AGENT_HOSTDIR}
        JENKINS_AGENT_SSH_PUBKEY: ${JENKINS_AGENT_SSH_PUBKEY}
    env_file:
      - path: .env
        required: true
    volumes:
      - ${JENKINS_AGENT_HOSTDIR}-0:${JENKINS_AGENT_WORKDIR}
      - ${JENKINS_AGENT_HOSTDIR}-0/var/run/docker.sock:/var/run/docker.sock
    expose:
      - 22
    ports:
      - 8081:8080
      - 50001:50000
    # environment:
    #   CONTAINER_NAME: jenkins-agent-0
    #   HOSTDIR: jenkins-agent-0.container

  jenkins-agent-1:
    container_name: jenkins-agent-1
    networks:
      jenkins-network:
        aliases:
          - jenkins-agent-1.service
    user: root
    privileged: true
    image: bernardbdas/jenkins-ssh-agent
    build:
      context: Dockerfiles
      dockerfile: agent.Dockerfile
      args:
        # CONTAINER_NAME: ${JENKINS_AGENT_CONTAINER_NAME}-1
        IMAGE_TYPE: ${JENKINS_SERVER_IMAGE_TYPE}
        IMAGE_TAG: ${JENKINS_SERVER_IMAGE_TAG}
        WORKDIR: ${JENKINS_SERVER_WORKDIR}
        HOSTDIR: /1-${JENKINS_AGENT_HOSTDIR}
        JENKINS_AGENT_SSH_PUBKEY: ${JENKINS_AGENT_SSH_PUBKEY}
    env_file:
      - path: .env
        required: true
    volumes:
      - ${JENKINS_AGENT_HOSTDIR}-1:${JENKINS_AGENT_WORKDIR}
      - ${JENKINS_AGENT_HOSTDIR}-1/var/run/docker.sock:/var/run/docker.sock
    expose:
      - 22
    ports:
      - 8082:8080
      - 50002:50000
    # environment:
    #   CONTAINER_NAME: jenkins-agent-1
    #   HOSTDIR: jenkins-agent-1.container

networks:
  jenkins-network:
    driver: bridge
